api-app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'spotify/search' => 'spotify#search'

end

api-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

api-app/app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
	def search
		title = params[:title]
		
		@artists = []
		@tracks = []
		
		if title
			@artists = RSpotify::Artist.search(title)
			@tracks = RSpotify::Track.search(title)
		end
	end
end

api-app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

api-app/app/helpers/application_helper.rb
module ApplicationHelper
end

api-app/app/helpers/spotify_helper.rb
module SpotifyHelper
end

api-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

api-app/app/views/layouts/_footer.html.erb
		<!-- Bootstrap core JavaScript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster 
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
	    <!-- <script src="/static/js/jquery.min.js"></script> -->
	    <!-- <script>window.jQuery || document.write('<script src=""><\/script>')</script> -->
	    <!-- <script src="/static/js/bootstrap.min.js"></script> -->
	    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
	    <script src="/static/js/ie10-viewport-bug-workaround.js"></script> -->
	</body>
</html>

api-app/app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Contactos - Inicio</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap core CSS -->
    <!-- <link href="/static/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="/static/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <style>
      body {
        min-height: 2000px;
        padding-top: 70px;
      }
    </style>
    
  </head>

api-app/app/views/layouts/application.html.erb
<%= render "layouts/header" %>

<body>

	<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">APIs</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
	          <ul class="nav navbar-nav">
	            <li class=""><a href="/">Home</a></li>
	            <li><a href="/spotify/search">Spotify</a></li>
	          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <%= yield %>

    <%= render "layouts/footer" %>

api-app/app/views/spotify/search.html.erb
<div class="container">

    <h1 id="helper-classes" class="page-header">Artists/Tracks</h1>

    <%= form_tag(spotify_search_path, method: :get) do %>
		<%= text_field_tag :title %>
		<%= submit_tag 'Search' %>
	<% end %>

	<h1 id="helper-classes" class="page-header">Search term: <%= params[:title] %></h1>

    <% if !@artists.blank? %>
    	<h1 id="helper-classes" class="page-header">Artists: </h1>

    	<table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
            <% @artists.each do |artist| %>
                <tr>
                    <td><%= artist.name %></td>
                    <td scope="row"><%= artist.id %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    <% end %>

    <% if !@tracks.blank? %>
    	<h1 id="helper-classes" class="page-header">Tracks: </h1>

        	<table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
            <% @tracks.each do |track| %>
                <tr>
                    <td><%= track.name %></td>
                    <td scope="row"><%= track.id %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    <% end %>    
</div>

api-app/app/views/welcome/index.html.erb
<div class="container">

  <div class="jumbotron">
    <h1>Rails API Test</h1>
    <p>This is an example application that uses some public API and their gems in order to test some basic features.</p>
    <p>Some of the APIs are:.</p>
    <ul>
      <li><a href="/spotify/search">Spotify : Rspotify(gem)</a></li>
    </ul>
  </div>

</div> <!-- /container -->